name: Update GitHub Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # প্রতিদিন রাত 12টায় auto রান হবে

permissions:
  contents: write # push করার অনুমতি

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      # Generate Stats Images
      - name: Generate Stats images
        run: |
          mkdir -p assets
          # GitHub Stats
          curl -o assets/github-stats.svg "https://github-readme-stats.vercel.app/api?username=jmfaheemhasan&show_icons=true&theme=radical"
          # Top Languages
          curl -o assets/top-langs.svg "https://github-readme-stats.vercel.app/api/top-langs/?username=jmfaheemhasan&layout=compact&theme=radical"
          # GitHub Streak (public-only)
          curl -o assets/streak-stats.svg "https://nirzak-streak-stats.demolab.com?user=jmfaheemhasan&theme=radical"

      # Commit & Push changes
      - name: Commit & Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add assets/
          git commit -m "Update GitHub stats [skip ci]" || echo "No changes to commit"

          git push https://x-access-token:$GITHUB_TOKEN@github.com/${{ github.repository }} HEAD:main



